// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using approvals.infrastructure.Persistence;

#nullable disable

namespace approvals.infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250608214810_approvals")]
    partial class approvals
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("approvals.domain.Entities.ApprovalInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CurrentStageOrder")
                        .HasColumnType("int");

                    b.Property<string>("OverallStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId");

                    b.ToTable("ApprovalInstance", (string)null);
                });

            modelBuilder.Entity("approvals.domain.Entities.ApprovalTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ApprovalTemplate", (string)null);
                });

            modelBuilder.Entity("approvals.domain.Entities.StageDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AssignmentKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AssignmentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ParallelAllowed")
                        .HasColumnType("bit");

                    b.Property<int>("SequenceOrder")
                        .HasColumnType("int");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId", "SequenceOrder")
                        .IsUnique();

                    b.ToTable("StageDefinition", (string)null);
                });

            modelBuilder.Entity("approvals.domain.Entities.StageInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AssignedTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("InstanceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StageDefId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("StageDefId");

                    b.HasIndex("InstanceId", "StageDefId")
                        .IsUnique();

                    b.ToTable("StageInstance", (string)null);
                });

            modelBuilder.Entity("approvals.domain.Entities.ApprovalInstance", b =>
                {
                    b.HasOne("approvals.domain.Entities.ApprovalTemplate", "Template")
                        .WithMany("ApprovalInstances")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("approvals.domain.Entities.StageDefinition", b =>
                {
                    b.HasOne("approvals.domain.Entities.ApprovalTemplate", "Template")
                        .WithMany("StageDefinitions")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("approvals.domain.Entities.StageInstance", b =>
                {
                    b.HasOne("approvals.domain.Entities.ApprovalInstance", "Instance")
                        .WithMany("StageInstances")
                        .HasForeignKey("InstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("approvals.domain.Entities.StageDefinition", "StageDefinition")
                        .WithMany("StageInstances")
                        .HasForeignKey("StageDefId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Instance");

                    b.Navigation("StageDefinition");
                });

            modelBuilder.Entity("approvals.domain.Entities.ApprovalInstance", b =>
                {
                    b.Navigation("StageInstances");
                });

            modelBuilder.Entity("approvals.domain.Entities.ApprovalTemplate", b =>
                {
                    b.Navigation("ApprovalInstances");

                    b.Navigation("StageDefinitions");
                });

            modelBuilder.Entity("approvals.domain.Entities.StageDefinition", b =>
                {
                    b.Navigation("StageInstances");
                });
#pragma warning restore 612, 618
        }
    }
}
