// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using approvals.infrastructure.Persistence;

#nullable disable

namespace approvals.infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260124230437_stageInstances")]
    partial class stageInstances
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("approvals.domain.Entities.ApprovalInstance", b =>
                {
                    b.Property<Guid>("InstanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentStageOrder")
                        .HasColumnType("integer");

                    b.Property<string>("OverallStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid");

                    b.Property<string>("TemplateName")
                        .HasColumnType("text");

                    b.HasKey("InstanceId");

                    b.HasIndex("TemplateId");

                    b.ToTable("ApprovalInstances");
                });

            modelBuilder.Entity("approvals.domain.Entities.ApprovalTemplate", b =>
                {
                    b.Property<Guid>("TemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TemplateId");

                    b.ToTable("ApprovalTemplates");
                });

            modelBuilder.Entity("approvals.domain.Entities.StageDefinition", b =>
                {
                    b.Property<Guid>("StageDefId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AssignmentKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AssignmentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SequenceOrder")
                        .HasColumnType("integer");

                    b.Property<string>("StageName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid");

                    b.HasKey("StageDefId");

                    b.HasIndex("TemplateId");

                    b.ToTable("StageDefinitions");
                });

            modelBuilder.Entity("approvals.domain.Entities.StageInstance", b =>
                {
                    b.Property<Guid>("StageInstanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApprovalInstanceId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssignedApproverId")
                        .HasColumnType("uuid");

                    b.Property<string>("Comments")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SequenceOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("StageDefId")
                        .HasColumnType("uuid");

                    b.Property<string>("StageName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("StageInstanceId");

                    b.HasIndex("ApprovalInstanceId");

                    b.HasIndex("StageDefId");

                    b.ToTable("StageInstances");
                });

            modelBuilder.Entity("approvals.domain.Entities.ApprovalInstance", b =>
                {
                    b.HasOne("approvals.domain.Entities.ApprovalTemplate", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("approvals.domain.Entities.UserInfo", "CreatedBy", b1 =>
                        {
                            b1.Property<Guid>("ApprovalInstanceInstanceId")
                                .HasColumnType("uuid");

                            b1.Property<string>("FullName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.HasKey("ApprovalInstanceInstanceId");

                            b1.ToTable("ApprovalInstances");

                            b1.WithOwner()
                                .HasForeignKey("ApprovalInstanceInstanceId");
                        });

                    b.Navigation("CreatedBy")
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("approvals.domain.Entities.StageDefinition", b =>
                {
                    b.HasOne("approvals.domain.Entities.ApprovalTemplate", "Template")
                        .WithMany("StageDefinitions")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("approvals.domain.Entities.StageInstance", b =>
                {
                    b.HasOne("approvals.domain.Entities.ApprovalInstance", "ApprovalInstance")
                        .WithMany("StageInstances")
                        .HasForeignKey("ApprovalInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("approvals.domain.Entities.StageDefinition", "StageDefinition")
                        .WithMany()
                        .HasForeignKey("StageDefId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApprovalInstance");

                    b.Navigation("StageDefinition");
                });

            modelBuilder.Entity("approvals.domain.Entities.ApprovalInstance", b =>
                {
                    b.Navigation("StageInstances");
                });

            modelBuilder.Entity("approvals.domain.Entities.ApprovalTemplate", b =>
                {
                    b.Navigation("StageDefinitions");
                });
#pragma warning restore 612, 618
        }
    }
}
