// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using approvals.infrastructure.Persistence;

#nullable disable

namespace approvals.infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("approvals.domain.Entities.ApprovalInstance", b =>
                {
                    b.Property<Guid>("InstanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CurrentStageOrder")
                        .HasColumnType("int");

                    b.Property<string>("OverallStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("InstanceId");

                    b.ToTable("ApprovalInstances");
                });

            modelBuilder.Entity("approvals.domain.Entities.ApprovalTemplate", b =>
                {
                    b.Property<Guid>("TemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TemplateId");

                    b.ToTable("ApprovalTemplates");
                });

            modelBuilder.Entity("approvals.domain.Entities.StageDefinition", b =>
                {
                    b.Property<Guid>("StageDefId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AssignmentKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AssignmentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SequenceOrder")
                        .HasColumnType("int");

                    b.Property<string>("StageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("StageDefId");

                    b.HasIndex("TemplateId");

                    b.ToTable("StageDefinitions");
                });

            modelBuilder.Entity("approvals.domain.Entities.StageInstance", b =>
                {
                    b.Property<Guid>("StageInstanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApprovalInstanceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SequenceOrder")
                        .HasColumnType("int");

                    b.Property<Guid>("StageDefId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StageInstanceId");

                    b.HasIndex("ApprovalInstanceId");

                    b.HasIndex("StageDefId");

                    b.ToTable("StageInstances");
                });

            modelBuilder.Entity("approvals.domain.Entities.StageDefinition", b =>
                {
                    b.HasOne("approvals.domain.Entities.ApprovalTemplate", "Template")
                        .WithMany("StageDefinitions")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("approvals.domain.Entities.StageInstance", b =>
                {
                    b.HasOne("approvals.domain.Entities.ApprovalInstance", "ApprovalInstance")
                        .WithMany("StageInstances")
                        .HasForeignKey("ApprovalInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("approvals.domain.Entities.StageDefinition", "StageDefinition")
                        .WithMany()
                        .HasForeignKey("StageDefId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApprovalInstance");

                    b.Navigation("StageDefinition");
                });

            modelBuilder.Entity("approvals.domain.Entities.ApprovalInstance", b =>
                {
                    b.Navigation("StageInstances");
                });

            modelBuilder.Entity("approvals.domain.Entities.ApprovalTemplate", b =>
                {
                    b.Navigation("StageDefinitions");
                });
#pragma warning restore 612, 618
        }
    }
}
