name: menagn.identitypro.pipeline

on:
  push:
    branches: [ "main" ]
    paths:
      - 'services/security.api/**'
    paths-ignore:
      - README.md
      - .gitignore
      - .dockerignore
      - ./services/platform.ui 
  pull_request:
    branches: [ "main" ]
    paths:
      - 'services/security.api/**'
    paths-ignore:
      - README.md
      - .gitignore
      - .dockerignore
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU for multi-architecture builds
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: services/security.api
          file: services/security.api/security.api/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/identitypro:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/identitypro:${{ github.run_number }}
