name: menagn.ui pipeline

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - README.md
      - .gitignore
      - .dockerignore
      - ./services/platform.api
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - README.md
      - .gitignore
      - .dockerignore
      - ./services/platform.api
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Build the Angular app
        run: npm run build -- --configuration=production

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Debug Docker Login
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker buildx build --push \
            --tag ${{ secrets.DOCKER_USERNAME }}/platform.ui:latest \
            -f ./Dockerfile .

      - name: Deploy to production
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          ssh -o StrictHostKeyChecking=no user@your-server.com << 'EOF'
          docker pull ${{ secrets.DOCKER_USERNAME }}/platform.ui:latest
          docker stop platform-ui || true
          docker rm platform-ui || true
          docker run -d -p 8000:8000 --name platform-ui ${{ secrets.DOCKER_USERNAME }}/platform.ui:latest
          EOF
